spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: user
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  security:
    issuers:
      - http://localhost:8089/idp/realms/user/protocol/openid-connect/certs
      - http://localhost:8089/idp/realms/user/protocol/openid-connect/certs
    jwk-set-uris:
      - http://localhost:8089/idp/realms/user/protocol/openid-connect/certs
      - http://localhost:8089/idp/realms/user/protocol/openid-connect/certs
app:
  security:
    issuers:
      - http://localhost:8089/idp/realms/user/protocol/openid-connect/certs
      - http://localhost:8089/idp/realms/user/protocol/openid-connect/certs
    jwk-set-uris:
      - http://localhost:8089/idp/realms/user/protocol/openid-connect/certs
      - http://localhost:8089/idp/realms/user/protocol/openid-connect/certs

#  kafka:
#    bootstrap-servers: localhost:9093
#    consumer:
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: '*'
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 8080
