openapi: 3.0.3
info:
  title: User API
  version: 1.0.0
paths:
  /users:
    post:
      summary: Create a user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDto'
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto'
  /users/{username}:
    get:
      summary: Get user by username
      operationId: getUser
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto'
        '404':
          description: User not found
components:
  schemas:
    AddressDto:
      type: object
      properties:
        address:
          type: string
        number:
          type: string
        city:
          type: string
        postalCode:
          type: string
        country:
          type: string
      required:
        - address
        - number
        - city
        - postalCode
        - country

    UserDto:
      type: object
      properties:
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        address:
          $ref: '#/components/schemas/AddressDto'
      required:
        - username
        - firstName
        - lastName
        - address
